# -*- coding: utf-8 -*-
"""ECE594BB_HW1_P1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zuYWxBe60aRNEP-Q05GxG1z9sJHr7m9Z
"""

import numpy as np
import matplotlib.pyplot as plt

# LIF parameters
V_rest = -65 #resting membrane potential (mV)
R = 1e6 # resistance (Ω)
tau = 50 # time constant (ms)
dt = 0.1 # unit time (ms)
n_steps = 20000 # time steps
V_th = -20 # threshold voltage (mV)

# membrane potential
V = np.zeros(n_steps)
V[0] = V_rest

# input current
I = np.zeros(n_steps)
I[5000:15000] = 5e-5 #(mA)

# spike train
spikes = np.zeros(n_steps)

for i in range(1, n_steps):
    if V[i - 1] >= V_th:
        V[i] = V_rest
        spikes[i - 1] = 1 # (mV)
    else:
        V[i] = V[i - 1] + dt/tau * (R * I[i - 1] - V[i - 1] + V_rest)

t = [n * dt for n in range(n_steps)]
plt.plot(t, V)
plt.axhline(y=V_th, color='r', linestyle='dashed')
plt.legend([r'$V(t)$', r'$V_{th}$'])
plt.title('LIF Neuron Simulation')
plt.xlabel('t (ms)')
plt.ylabel('V (mV)')

print(np.count_nonzero(spikes))